### vars
@port = 3001
@localhost = http://localhost:{{port}}/api/v1
@contentType = application/json

###
# POST {{localhost}}/register
content-type: {{contentType}}

{
    "email": "jordan+20@knight.works",
    "password": "test",
    "site": "admin.knight.works"
}